-- MySQL Script generated by MySQL Workbench
-- Sat Feb  1 19:49:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mangosystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mangosystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mangosystem` DEFAULT CHARACTER SET utf8 ;
USE `mangosystem` ;

-- -----------------------------------------------------
-- Table `mangosystem`.`__efmigrationshistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangosystem`.`__efmigrationshistory` (
  `MigrationId` VARCHAR(95) NOT NULL,
  `ProductVersion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mangosystem`.`mangouserclaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangosystem`.`mangouserclaims` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserId` INT(11) NOT NULL,
  `ClaimType` VARCHAR(15) NULL DEFAULT NULL,
  `ClaimValue` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mangosystem`.`mangouserroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangosystem`.`mangouserroles` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `IX_MangoUserRoles_RoleName` (`RoleName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mangosystem`.`mangousers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangosystem`.`mangousers` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `LoginName` VARCHAR(20) NULL DEFAULT NULL,
  `UserName` VARCHAR(20) NULL DEFAULT NULL,
  `Password` LONGTEXT NULL DEFAULT NULL,
  `Email` VARCHAR(40) NULL DEFAULT NULL,
  `CreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `LastLoginDate` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `IX_MangoUsers_UserName` (`UserName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mangosystem`.`user2roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangosystem`.`user2roles` (
  `UserId` INT(11) NOT NULL,
  `RoleId` INT(11) NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
