version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nuget_user: q932104843@outlook.com
  nuget_password:
    secure: V8cfjt1fzh1e4N3+bJuWJg==
build_script:
- ps: dotnet build -c Release
deploy: off