# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'key.json'

    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'localhost.pfx'

    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'mangoidentity.pfx'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.SourcesDirectory)/MangoAccountSystem'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/MangoAccountSystem/Dockerfile'
        tags: |
          $(tag)
    
    - task: Docker@2
      displayName: Docker Push
      inputs:
        containerRegistry: 'aliyunDockerHub'
        repository: 'chiva_mg_namespace/chiva_mg_repository'